###
POST http://localhost:8000/order HTTP/1.1
Content-Type: application/json

{
    "id": "26c07f62-5266-464d-a724-6bfe6eb02166",
    "price": 20.5,
    "tax": 0.3
}

###
GET http://localhost:8000/order HTTP/1.1
Content-Type: application/json